# Generated by Django 6.0.6 on 2026-07-04 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=20)),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('alamat', models.TextField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.kelas')),
            ],
        ),
    ]
