# Generated by Django 6.0.6 on 2026-07-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='jurusan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kelas',
            name='tingkat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
