# Generated by Django 6.0.6 on 2026-07-18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('siswa', '0002_kelas_jurusan_kelas_tingkat'),
    ]

    operations = []


