# Generated by Django 6.0.6 on 2026-07-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0003_add_import_kelas_after_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='jenis_kelamin',
            field=models.CharField(max_length=17),
        ),
    ]
