# Generated by Django 6.0.6 on 2026-08-08 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0004_siswa_no_alter_siswa_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='alfa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siswa',
            name='hadir',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siswa',
            name='izin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nilai_akhir',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='sakit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siswa',
            name='status_kelulusan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='terlambat_tugas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siswa',
            name='tugas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siswa',
            name='uas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siswa',
            name='uts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to='siswa.kelas'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
