# Generated by Django 6.0.6 on 2026-08-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0005_siswa_alfa_siswa_hadir_siswa_izin_siswa_nilai_akhir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('nama_asli', models.CharField(max_length=255)),
                ('jumlah_data', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
